### ISSUE TITLE
Imapsync with docker compose v2

### ISSUE THREAD

**Issue by Boostflow** [imapsync/imapsync#262]
I can't seem to find any reference / example of how to run the CMD commands using docker compose. Trying to run this in docker compose:

```
imapsync \
     --host1 test1.lamiral.info --user1 test1 --password1 secret1 \
     --host2 test2.lamiral.info --user2 test2 --password2 secret2
```

I expect something like this:

```
version = '2'
services
 imapsync:
   container_name: imapsync
   image: gilleslamiral/imapsync:latest
   restart: unless-stopped
   command: imapsync && --host1 test1.lamiral.info --user1 test1 --password1 secret1 --host2 test2.lamiral.info --user2 test2 --password2 secret2
```

Also tried it including bash -c

```
version = '2'
services
 imapsync:
   container_name: imapsync
   image: gilleslamiral/imapsync:latest
   restart: unless-stopped
   command: bash -c  "imapsync && --host1 test1.lamiral.info --user1 test1 --password1 secret1 --host2 test2.lamiral.info --user2 test2 --password2 secret2"
```

but to no success. Does anyone have a working compose example or can steer me in the right direction?

**Comment by gilleslamiral** [comment]
What is this "&&" after imapsync command?

**Comment by Boostflow** [comment]
I found that option brings my docker a bit further on execution. With "&&" I (wrongfully) assumed imapsync and --host1 were to separate commands. However, I did get it to run. This is what is working for compose V2, I was missing ''

```
version = '2'
services
  imapsync:
    container_name: imapsync
    image: gilleslamiral/imapsync:latest
    restart: unless-stopped
    command: 'imapsync --host1 test1.lamiral.info --user1 test1 --password1 secret1 --host2 test2.lamiral.info --user2 test2 --password2 secret2'
    logging:
     options:
       max-size: 50m
    dns: xxx.xxx.xxx.xxx
    networks:
      macvlan_lan:
        ipv4_address: xxx.xxx.xxx.xxx
```
