### ISSUE TITLE
Sync missing messages and no log 

### ISSUE THREAD

**Issue by SheepDomination** [imapsync/imapsync#479]
When doing the sync _234_ messages were not synced. Also I added the `--log` to the command option but no log is shown as completed ?

**Comment by gilleslamiral** [comment]
> When doing the sync _234_ messages were not synced. Also I added the `--log` to the command option but no log is shown as completed ?

I don't understand. There is a log by default. What is your context?

**Comment by SheepDomination** [comment]
```
imapsync:
        ports:
 
        image: gilleslamiral/imapsync 
        volumes: 

        command: /servimapsync --logdir ""
```

Above is my docker compose but where do I place `--logdir` ?
